title: "UVA \"Brainhack\" 2025"
description: "Weekly coding/neuroimaging workshops hosted by the Morris and Connelly Labs at the University of Virginia."
remote_theme: pages-themes/hacker@v0.2.0
plugins: 
  - jekyll-remote-theme
